<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="true" />
<meta name="allow-skip" content="true" />

<title>Generalised Linear Models</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-lets-start-from-the-beginning" class="section level2">
<h2>Let’s start from the beginning</h2>
<p>None of us can know the future, but statisticians have the magic power to predict it! Their super power is called “regression analysis”. Basically, what regression analysis does is to fit a model to data and use it to predict values of the dependent variable (DV) from one or more independent variables (IVs). Regression analysis is a way of predicting an outcome variable from one predictor variable (simple regression) or several predictor variables (multiple regression). This tool is incredibly useful because it allows statisticians (and researchers in general!) to go a step beyond the data that they collected.</p>
<p>
 
</p>
</div>
<div id="section-modeling-the-pisa-data" class="section level2">
<h2>Modeling the PISA Data</h2>
<p>In this section, we will outline how to use linear models to analyse the PISA data and make prediction based on the data collected. We will briefly cover general linear models before progressing to generalised linear models. Once we have looked at general and generalised linear models, we will look at Linear Mixed Models before finally covering Generalised Linear Mixed Models. By the end of this section you should have a solid grasp of the key concepts required to create your own models to analyse your data.</p>
<p>
 
</p>
<div id="section-loading-in-and-sorting-the-data" class="section level3">
<h3><strong>Loading in and sorting the data</strong></h3>
<p>Before we begin modelling the data, we first need to sort the data. Sorting the data can make it much more manageable to analyse. This can help in fitting and understanding the models that we create. In our example below we will be loading in two different data sets relating to the PISA data. ###ask what they meant We will firstly load in the data on time spent in the classroom and the amount of spending on education by each country. To sort the data we will standardize the columns that we want to use as predictors. By standardizing the variables, we transform them so that they are measured on a scale of standard units. This is beneficial when our data is not measured on the same scale. When data data becomes standardized everything becomes internally consistent and this can make it much easier to directly compare our variables. In order to standardize the data we can use the <code>scale()</code> function. As well as the scale function, we will use the <code>transformTukey()</code> function on the spending variable. This is because the spending data is not normally distributed and by applying the transformTukey function we are able to normalize it a bit before it is standardized.</p>
<pre class="r"><code># load in the data
dat_learn_spend &lt;- read_csv(&quot;learn_spend_data.csv&quot;) %&gt;%
# use filter to select only the rows where there are no N/As
  filter(!is.na(.$Spending) &amp; !is.na(.$Learning)) %&gt;%
# Scale the data
  mutate(Spending = scale(transformTukey(Spending)),
         Learning = scale(Learning), 
# Change the name of the Code column to CNT in order to allow it to be joined to the other data later
         CNT = Code) %&gt;%
# Select the relevant columns needed for the analysis
  select(c(Country, CNT, Spending, Learning))</code></pre>
<p>
 
</p>
<p>By running the above code, 3 graphs appear showing the transformed data. These three graphs show the distribution of the spending data points. From the data it can be seen that there is a slight positive skew. This can be seen with the first plot which shows a much more gradual slope as the lambda approaches zero compared to when lambda passes zero and in the qq plot where most of the points appear to be below the red line.</p>
<p>Now that we have sorted the data we can now load in the second data set. Whilst loading in the data, we will again standardize it. We will also need to select the specific columns that we wish to use and also set one of those columns as a factor so it can later be used in the analysis. The columns that we want from this data set are all the columns relating to the reading scores of the countries, the ESCS column relating to the Economic social and cultural status of each country, the ATTLNACT column relating to the attitudes towards education within each country and finally, the ID column. For the analysis we need to scales the ESCS column and the ATTLNACT column. We also need to set the ID column as a factor for this analysis.</p>
<pre class="r"><code># Load in the second data set
dat_pisa &lt;- read_csv(&quot;pisa18_data1.csv&quot;) %&gt;%
# select the columns we want for the analysis  
  select(contains(&quot;READ&quot;), ESCS, ATTLNACT, ID=X1, CNT) %&gt;%
# remove any rows containing N/As
    na.omit() %&gt;%
# standardize the data
      mutate(ESCS = scale(ESCS), 
             ATTLNACT = scale(ATTLNACT), 
# Set ID as a factor
             ID = as.factor(ID))</code></pre>
<p>
 
</p>
<p>Now that we have sorted the two data sets, we need to combine them in order to analyse the data. We can join the two columns using the <code>inner_join()</code> function. Once we have joined the two tables together we can change them from a wide format to a long one using the <code>gather()</code> function. By doing this we are able to create a score and item column. This allows us to see each of the countries score on each of the reading items. In our code we have used the function <code>sample_n(4e2)</code>. This function allows us to select a random sample from the data set. We are simply doing this to reduce the amount of data points in our examples as using all of the data would cause the fitted models in the following sections to take a very long time to run.</p>
<pre class="r"><code># Join the tables togehther
read_data &lt;- inner_join(dat_pisa, dat_learn_spend, by = &quot;CNT&quot;) %&gt;%
  sample_n(4e2) %&gt;%
# Change the data from wide to long format
    gather(&quot;Item&quot;, &quot;Score&quot;, 1:10)</code></pre>
<p>
 
</p>
<p>Now that we have joined the two tables, we can move on to our analysis. The main point that should be gained from this section is that it is important to standardize the data before performing a complex analysis.</p>
<p>
 
</p>
<div id="section-sorting-data-exercise" class="section level4">
<h4><strong>Sorting data exercise</strong></h4>
<p><div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div></p>
<div class="panel panel-default">
<div data-label="sorting_exercise-1" class="tutorial-question panel-body">
<div id="sorting_exercise-1-answer_container" class="shiny-html-output"></div>
<div id="sorting_exercise-1-message_container" class="shiny-html-output"></div>
<div id="sorting_exercise-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="sorting_exercise-2" class="tutorial-question panel-body">
<div id="sorting_exercise-2-answer_container" class="shiny-html-output"></div>
<div id="sorting_exercise-2-message_container" class="shiny-html-output"></div>
<div id="sorting_exercise-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>
 
</p>
<p>
 
</p>
</div>
</div>
</div>
<div id="section-simple-models" class="section level2">
<h2><strong>Simple models</strong></h2>
<p>Now that we have sorted the data appropriately we can begin the analysis. A good point to start when beginning an analysis is to visualize the data. In this case we can begin by visualizing the distribution of the scores (the dependent variable in our data). In order to do this we can create a histogram.</p>
<p><img src="GLM_Tutorial_files/figure-html/histogram%20of%20scores-1.png" width="624" /></p>
<p>
 
</p>
<p>
 
</p>
<p>From the histogram it appears that the data is slightly negatively skewed. This would suggest that the use of a standard linear model may not be the best approach. Despite this we can still fit one and see how it deals with the data.</p>
<p>
 
</p>
<p>
 
</p>
<p>And now let’s start with the analysis!</p>
<p>For our linear model we will use the <code>lm()</code> function. Form our data set, our Score column will be our dependent variable, whilst the Spending, learning, ESCS, ATTLNACT and Item columns will be used as our independent variables (predictors).</p>
<p>
 
</p>
<p>
 
</p>
<p>Firstly, we will create a model with a single predictor. For example, if we want to know how the Spending variable predicts the Score, we have to build our analisys in this way:</p>
<pre><code>## 
## Call:
## lm(formula = Score ~ Spending, data = read_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -320.53  -64.98    5.75   70.62  303.74 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  485.436      1.552   312.9   &lt;2e-16 ***
## Spending      37.635      1.734    21.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 97.97 on 3998 degrees of freedom
## Multiple R-squared:  0.1054, Adjusted R-squared:  0.1051 
## F-statistic: 470.8 on 1 and 3998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation: Let’s look first at the R2 statistics. This value describes the overall model (so it tells us whether the model is successful in predicting “Score”). The value of R2 is a measure of how much of the variability in the outcome is accounted for by the predictors. For the first model its value is .105 which means that “Spending” accounts for 10.5% of the variation in “Scores”. That means that 89.5% of the variation in “Score” can not be explained by advertising alone. Therfore, there must be other variables that have an influence also. The result of ANOVA for these data is significant, so the model results in a significantly good degree of prediction of the outcome variable. However, the ANOVA doesn’t tell us about the individual contribution of variables in the model (in this simple case, only one variable).</p>
<p>Coefficients contains the model parameters (the beta values) and the significance of these values. In regression equation, b0 was the Y intercept and this values is the value in the Estimate colum for the (intercept). It is in brackets because it’s not a real variable. We can say that b0 is 485.44, and this can be interpreted as meaning that wen no “Spending” is done (when X= 0), the model predicts that 485.44 Score would be achieve. We can also read off the value of b1 from the row labelled Spending and this value represent the gradient of the regression line. It is 37.64. Although this value is the slope of the regression line, it is more useful to think of this value as representing the change in the outcome associated with a unit change in the predictor. Therefore, if our predictor variable (“Spending”) is increased by one unit, our model predicts that “Score” will increase 37.63. We also see that the t-test tells us whether the b-value is different from 0. For this variable, we can conclude that the “Spending” makes a significant contribution (p&lt;.001) to predicting “Score”.</p>
<p>We can see in “Spending” raw.</p>
<p>The adjusted R2 gives us some idea of how well our model generalizes, and ideally we would like its value to be the same, or very close to, the value of R2. In this example the difference for the model is small (0,0003)</p>
<p>
 
</p>
<p>
 
</p>
<pre><code>## 
## Call:
## lm(formula = Score ~ ATTLNACT, data = read_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -292.08  -76.28    6.97   75.93  324.85 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  483.249      1.642 294.310   &lt;2e-16 ***
## ATTLNACT       3.235      1.719   1.882   0.0599 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 103.5 on 3998 degrees of freedom
## Multiple R-squared:  0.0008849,  Adjusted R-squared:  0.000635 
## F-statistic: 3.541 on 1 and 3998 DF,  p-value: 0.05995</code></pre>
<p>What is have explained for the former linear regression could be applied to that.Do this model explain more or less of the variability in the outcome “Score”?</p>
<p>
 
</p>
<p>
 
</p>
<p>Well, you know, reality is a much more complex model. So we need to build models with more than a single predictor. It is certainly possible that taken together Spending and ATTLNACT explain more about Score than either predictor alone.</p>
<pre><code>## 
## Call:
## lm(formula = Score ~ Spending + ATTLNACT, data = read_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -316.46  -65.70    5.37   71.65  307.89 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  485.047      1.554 312.145  &lt; 2e-16 ***
## Spending      38.004      1.736  21.896  &lt; 2e-16 ***
## ATTLNACT       5.483      1.628   3.369 0.000762 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 97.84 on 3997 degrees of freedom
## Multiple R-squared:  0.1079, Adjusted R-squared:  0.1074 
## F-statistic: 241.7 on 2 and 3997 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>When the two predictors are included, the value of R2 (how much of the variability in the outcome is accounted for by the predictors) increase from 0.105 to 0.108. The b-values tell us that there is a significant positive relationship between both predictors and the outcome (both values are positive). Moreover, the b-values tell us to what degree each predictor affects the outcome if the effects of all other predictors are held constant: 1) “Score” would increases by 485.05 when “Spending” increases by one unit; 2) “Score” would increases by 5.548 when “ATTLNACT” increases by one unit. Both b-values are making a significant contribution to the model since corresponding t-test are significant. The larger value of t, the greater the contribution of that prediction. In this case, we can see that the “Spending” has greater impact than “ATTLNACT” in “Score”.</p>
<p>In the next step we will calculate interaction of both variables to know the contribution of it.</p>
<p>
 
</p>
<pre><code>## 
## Call:
## lm(formula = Score ~ Spending * ATTLNACT, data = read_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -313.442  -64.806    5.526   72.318  309.943 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        485.404      1.554 312.417  &lt; 2e-16 ***
## Spending            37.878      1.733  21.859  &lt; 2e-16 ***
## ATTLNACT             5.809      1.627   3.570 0.000361 ***
## Spending:ATTLNACT    6.740      1.704   3.954 7.81e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 97.66 on 3996 degrees of freedom
## Multiple R-squared:  0.1114, Adjusted R-squared:  0.1107 
## F-statistic: 166.9 on 3 and 3996 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Including the interaction, the value of R2 has increased from 0.108 to 0.11. The b-values tell us that there is a significant positive relationship between both predictors and their interaction with the outcome. If we see the value of t-test, the “Spending” is the factor with the higher contribution to the model.</p>
<p>
 
</p>
<p>
 
</p>
<p>Let’s try to include all the collected variables.</p>
<pre><code>## 
## Call:
## lm(formula = Score ~ Spending * Learning * ESCS * ATTLNACT + 
##     Item, data = read_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -288.467  -59.523    5.242   61.057  307.304 
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                     478.7019     4.6238 103.530  &lt; 2e-16 ***
## Spending                         13.6012     1.9845   6.854 8.31e-12 ***
## Learning                         -0.2226     2.3845  -0.093  0.92562    
## ESCS                             47.5601     2.1874  21.742  &lt; 2e-16 ***
## ATTLNACT                          3.9032     2.0419   1.912  0.05600 .  
## ItemPV1READ                       2.9673     6.2273   0.476  0.63375    
## ItemPV2READ                       0.2329     6.2273   0.037  0.97016    
## ItemPV3READ                       2.2951     6.2273   0.369  0.71248    
## ItemPV4READ                      -0.7590     6.2273  -0.122  0.90300    
## ItemPV5READ                       0.3200     6.2273   0.051  0.95902    
## ItemPV6READ                      -0.6009     6.2273  -0.096  0.92314    
## ItemPV7READ                       0.8478     6.2273   0.136  0.89172    
## ItemPV8READ                       1.4957     6.2273   0.240  0.81019    
## ItemPV9READ                       0.7619     6.2273   0.122  0.90263    
## Spending:Learning                 7.9995     3.0378   2.633  0.00849 ** 
## Spending:ESCS                     0.7239     2.0236   0.358  0.72056    
## Learning:ESCS                     1.6253     2.6189   0.621  0.53490    
## Spending:ATTLNACT                 1.7895     1.9925   0.898  0.36918    
## Learning:ATTLNACT                 3.5235     2.6496   1.330  0.18366    
## ESCS:ATTLNACT                    -4.6166     2.2257  -2.074  0.03812 *  
## Spending:Learning:ESCS           -1.1736     3.0892  -0.380  0.70405    
## Spending:Learning:ATTLNACT        3.0271     2.9634   1.021  0.30709    
## Spending:ESCS:ATTLNACT            1.9688     2.1781   0.904  0.36608    
## Learning:ESCS:ATTLNACT           -6.2025     3.3565  -1.848  0.06469 .  
## Spending:Learning:ESCS:ATTLNACT  -6.3685     3.3443  -1.904  0.05694 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 88.07 on 3975 degrees of freedom
## Multiple R-squared:  0.2812, Adjusted R-squared:  0.2769 
## F-statistic:  64.8 on 24 and 3975 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The output from the results appear to show that spending, and attitudes towards education are significant predictors and that there are significant two way interactions between spending and attitudes towards education, as well as between learning and attitudes towards education. There were also significant three way interactions between spending, learning, and economic social and cultural status and, spending, economic social and cultural status, and attitudes towards education. As mentioned above however, even if the linear regression is a magic way to predict the future, in this particular case, the data was negatively skewed and so this model may not be the best method for analysis.</p>
<p>
 
</p>
<div id="section-generalized-linear-models" class="section level3">
<h3>Generalized Linear Models</h3>
<p>An alternative approach to analyzing the PISA data could be to use a generalized linear model. A generalized linear model is similar to a general linear model, except some of the constraints are relaxed. This typically makes it better when dealing with data that is not normally distributed, such as is the case with the PISA data.</p>
<p>There are different family arguments that can be made when using a generalized linear model. These different families allow us to deal with data with different types of distributions. Family distributions include Gaussian (which is the bases of the linear model and ideal for normally distributed data), Binomial (which is useful when dealing with a binomial distribution), and Gamma (which is useful when there is skewed data). These are just a few of the families that can be applied when using a generalized linear model.</p>
<p>Since we are dealing with data that is negatively skewed we will use the Gamma family in our example. The code for using the glm is very similar to the code needed when creating a linear model. The only difference is now at the end of the code we specify the family and link arguments. Link arguments allow us to apply transformations to the model parameters and also determines the way the model coefficients are interpreted. Changing the link function can, in some cases, result in a better fitting model. There are many different link arguments for each family but for now we will just use the standard identity link.</p>
<pre class="r"><code># Use the glm finction to create a genearlised linear model
GLM_mod &lt;- glm(Score ~ Spending * Learning * ESCS * ATTLNACT + Item,
               data = read_data, 
# specify the family as gamma with an identity link
               family= Gamma(link = &quot;identity&quot;))
# Get the output from the generalised linear model
summary(GLM_mod)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Score ~ Spending * Learning * ESCS * ATTLNACT + 
##     Item, family = Gamma(link = &quot;identity&quot;), data = read_data)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -0.90019  -0.13104   0.00439   0.12767   0.55900  
## 
## Coefficients:
##                                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                     486.5152     4.7998 101.361  &lt; 2e-16 ***
## Spending                         26.3577     2.0405  12.917  &lt; 2e-16 ***
## Learning                          0.4280     2.3863   0.179   0.8577    
## ESCS                             27.5863     2.0885  13.209  &lt; 2e-16 ***
## ATTLNACT                          3.0047     2.0298   1.480   0.1389    
## ItemPV1READ                       0.4998     6.4532   0.077   0.9383    
## ItemPV2READ                      -1.4741     6.4392  -0.229   0.8189    
## ItemPV3READ                      -0.5713     6.4456  -0.089   0.9294    
## ItemPV4READ                      -0.3387     6.4472  -0.053   0.9581    
## ItemPV5READ                      -0.9090     6.4432  -0.141   0.8878    
## ItemPV6READ                      -1.8476     6.4366  -0.287   0.7741    
## ItemPV7READ                      -1.1848     6.4413  -0.184   0.8541    
## ItemPV8READ                       0.2317     6.4513   0.036   0.9713    
## ItemPV9READ                       1.4259     6.4597   0.221   0.8253    
## Spending:Learning                17.4008     2.9834   5.833 5.89e-09 ***
## Spending:ESCS                    -1.4277     1.9509  -0.732   0.4643    
## Learning:ESCS                   -10.0167     2.4943  -4.016 6.03e-05 ***
## Spending:ATTLNACT                 5.3574     2.0896   2.564   0.0104 *  
## Learning:ATTLNACT                -1.0406     2.3463  -0.443   0.6574    
## ESCS:ATTLNACT                    -4.6280     2.1525  -2.150   0.0316 *  
## Spending:Learning:ESCS           -6.8004     2.7844  -2.442   0.0146 *  
## Spending:Learning:ATTLNACT       -6.6104     2.7304  -2.421   0.0155 *  
## Spending:ESCS:ATTLNACT            2.2585     1.8969   1.191   0.2339    
## Learning:ESCS:ATTLNACT          -14.4538     2.4378  -5.929 3.31e-09 ***
## Spending:Learning:ESCS:ATTLNACT -17.6719     2.6886  -6.573 5.57e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Gamma family taken to be 0.03807456)
## 
##     Null deviance: 214.32  on 3999  degrees of freedom
## Residual deviance: 162.78  on 3975  degrees of freedom
## AIC: 47746
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>
 
</p>
<p>Here we can see that the output presented when we use the glm function is very similar to the output when we use the lm function. One of the main differences is to do with the goodness of fit statistic presented in the two outputs. when we use the lm function the goodness of fit statistic is given as the adjusted R-squared. with the glm function, the goodness of fit statistic given is the Akaike Information Criteria (AIC) score.</p>
<p>From the output we can see that there are differences in the significance values in the glm output compared to the lm output. In the glm output we now find that the there are significant main effects of spending, economic social and cultural status, and attitudes towards education. There is now significant two way interactions between learning and economic social and cultural status; spending and attitudes towards education and; economic social and cultural status and attitudes towards education. Significant three way interactions were also found between spending, learning and Economic social and cultural status, as well as between spending, economic social and cultural status, and attitudes towards education.</p>
<p>
 
</p>
</div>
<div id="section-model-comparison" class="section level3">
<h3><strong>Model comparison</strong></h3>
<p>Now that we have fitted a generalized linear model to the data we can check to see if it really fits the data better than our original linear model. There are multiple ways to do this. One of the simplest ways to compare the models is to look at the Akaike Information Criterion (AIC). This is a goodness of fit statistic which takes into account how well a model explains the data and adds a penalty for model complexity. AIC scores can be used to compare the goodness of fit of different models. The general rule when comparing models using AIC is that the model with the lowest AIC value fits the data better. The AIC is quite arbitrary however, as there are no set guidelines for using it. We can obtain the AIC value by using the <code>AIC()</code> function.</p>
<pre class="r"><code># run the AIC for the linear model
lm_AIC &lt;- AIC(LM_mod)
lm_AIC</code></pre>
<pre><code>## [1] 47522.13</code></pre>
<pre class="r"><code># Run the AIC for the generalised linear model
glm_AIC &lt;- AIC(GLM_mod)
glm_AIC</code></pre>
<pre><code>## [1] 47746.13</code></pre>
<p>
 
</p>
<p>From looking at our AIC values we find a rather interesting result. It appears that the Linear model has a lower AIC value than the Generalized linear model. In this case it would suggest that using a standard linear model would have a better fit than using using the gamma family with an identity link function.</p>
<p>
 
</p>
</div>
<div id="section-simple-model-exercises" class="section level3">
<h3><strong>Simple model exercises</strong></h3>
<p><div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div></p>
<div class="panel panel-default">
<div data-label="LM_Questions-1" class="tutorial-question panel-body">
<div id="LM_Questions-1-answer_container" class="shiny-html-output"></div>
<div id="LM_Questions-1-message_container" class="shiny-html-output"></div>
<div id="LM_Questions-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="LM_Questions-2" class="tutorial-question panel-body">
<div id="LM_Questions-2-answer_container" class="shiny-html-output"></div>
<div id="LM_Questions-2-message_container" class="shiny-html-output"></div>
<div id="LM_Questions-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="LM_Questions-3" class="tutorial-question panel-body">
<div id="LM_Questions-3-answer_container" class="shiny-html-output"></div>
<div id="LM_Questions-3-message_container" class="shiny-html-output"></div>
<div id="LM_Questions-3-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>
 
</p>
<p>
 
</p>
</div>
</div>
<div id="section-more-complex-models" class="section level2">
<h2>More complex Models</h2>
<p>Now that we have gone through simple model types we will look at more complex models. The next section will look at Linear Mixed Models (LMMs) and Generalised Linear Mixed Models (GLMMs). These two model types expand on the ideas from the simple models shown in the previous section but add additional options to help fit the data better. This tutorial will provide a brief overview of more complex models, however a more detailed explanation is given in a paper written by Barr et al., (2013).</p>
<p>One of the ways in which LMMs and GLMMs expand on the previous models covered in this tutorial is through the introduction of fixed and random effects. These can be introduced by classifying our independent variables as fixed or random effects. When we refer to a variable as a fixed effect, we assume that this variable remains constant across replications. In most cases the fixed effects that we select for our model are the main predictors that we wish to use to predict our independent variable. In the models that we are fitting to the PISA data, we assume that the Spending and the Learning variables are fixed effects as we assume that these would remain relatively constant among replications.</p>
<p>Random effects refer to the sources of random variation that may occur in our model. Random variation is the variation that occurs in our model even when we have controlled for everything. One major source of random variation within psychological experiments can be found with the participants as some participants may be better suited to some tasks than others. Another key source of variance in psychological experiments is the items used as some may be more effective for an experiment than others. This random variance means that scores of participants and on items may fluctuate in a random pattern. By using LMMs and GLMMs we can assign specific variables that may be sources of random variance as random effects. By doing this we are bale to account for the random variance that occurs within our models which in turn can help to make our model fit the data better than using more simple modelling techniques.</p>
<p>By assigning random effects in our models we can add random slopes and intercepts which help us to model the data better. By adding in random slopes we are allowing our fixed effects to vary based on each of the items within our random effects. Random intercepts allow for a variation in the scores obtained for each of the items within the random effects.</p>
<p>Suppose we ran a study in which 10 participants were asked to complete a stroop task. We could assign the students in the study as a random effect as some would naturally perform better than others. We could therefore add a random slope for each of the 10 participants. By doing this, in theory, we should create a better fitting model of the data as we are accounting for the performance of each individual participant on the task. We could also add in random intercepts for each of the 10 participants which would in turn allow us to account for the variance in the individual scores of each of the participants. By doing this we should therefore create a better fitting model as we are now accounting for the random variance that occurs due to the differences in abilities of the participants.</p>
<p>With the PISA data we could assume that the variable <code>country</code> is a random variable. We could assume that the different countries would create a random variance due to factors that are not controlled for within our models. We could also assume that <code>Item</code> is a random variable as we could assume that some items may be more effective than others in measuring the scores in each of the predictor variables.</p>
<p>
 
</p>
<p>Now that we have discussed the key differences between the simple linear models and the more complex models, let’s work through an example. The next section will go through the steps involved in running a Linear Mixed Model on the PISA data.</p>
<p>
 
</p>
<div id="section-linear-mixed-effect-model" class="section level3">
<h3><strong>Linear Mixed Effect Model</strong></h3>
<p>Setting up and running a linear mixed model (LMMs) is very similar to setting up and running a standard linear model. There are some key differences though. Base R does not have a function that can effectively deal with LMMs and so we have to use a different package. The package that is most commonly used to run LMMs is known as the <code>lme4</code> package. Once that package has been loaded in we can begin to create LMMs. The function within the lme4 package that is required is known as the <code>lmer()</code> function. Once we have selected this function we then have to tell it what model we want it to run. This is done in a similar way to that of the <code>lm()</code> function. We start by specifying the dependent variable, then we add in our predictors and finish by specifying our data. The differences appear when we want to add in our random effects. In order to add random effects we have to use the following input <code>(1|random effect)</code>. If we want to specify in our model that the random effect is interacting with our predictors, i.e we have within subjects interactions between certain fixed and random effects, then we can do it like this: <code>(1 + predictor|random effect)</code>.</p>
<p>In our example below, we have selected the same variables as before in the standard linear model for our dependent variable and our predictors. This time however, we have set the Country, Item and the ID as random effects. For the random effects we are taking into account the interaction between the random effect of Country and the fixed effect of Spending and Learning. We are also taking into account the interaction between the random effect of ID and the Economics Social and Cultural status; and the Attitudes towards education.</p>
<pre class="r"><code># Use lmer to run a linear mixed model
LMM_mod &lt;- lmer(Score ~ Spending * Learning * ESCS * ATTLNACT +
# Use the (1 + X|random variable) strucutre to add in the random effects
                   (1 + Spending * Learning | Country) +
                   (1 + ESCS * ATTLNACT | ID) + 
                   (1|Item),
                 data = read_data)
# Get a summary of the output
summary(LMM_mod)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Score ~ Spending * Learning * ESCS * ATTLNACT + (1 + Spending *  
##     Learning | Country) + (1 + ESCS * ATTLNACT | ID) + (1 | Item)
##    Data: read_data
## 
## REML criterion at convergence: 39261.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.2145 -0.6116 -0.0187  0.6109  4.3360 
## 
## Random effects:
##  Groups   Name              Variance Std.Dev. Corr             
##  ID       (Intercept)       7003.71  83.688                    
##           ESCS                 3.43   1.852    0.70            
##           ATTLNACT           551.15  23.477   -0.14 -0.76      
##           ESCS:ATTLNACT       68.03   8.248   -0.12  0.58 -0.97
##  Country  (Intercept)          0.00   0.000                    
##           Spending            26.75   5.172     NaN            
##           Learning           121.52  11.024     NaN  0.23      
##           Spending:Learning 1035.02  32.172     NaN -0.96  0.07
##  Item     (Intercept)          0.00   0.000                    
##  Residual                    685.45  26.181                    
## Number of obs: 4000, groups:  ID, 400; Country, 11; Item, 10
## 
## Fixed effects:
##                                 Estimate Std. Error t value
## (Intercept)                     483.3314     7.6789  62.943
## Spending                         20.1796     7.5688   2.666
## Learning                         -1.2931    12.4731  -0.104
## ESCS                             31.1926     6.5245   4.781
## ATTLNACT                          3.8797     6.5969   0.588
## Spending:Learning                 6.4015    18.6473   0.343
## Spending:ESCS                     0.6221     6.1352   0.101
## Learning:ESCS                    -7.8797     7.3533  -1.072
## Spending:ATTLNACT                 7.7160     6.6889   1.154
## Learning:ATTLNACT                 1.2336     7.4247   0.166
## ESCS:ATTLNACT                    -9.4856     6.9283  -1.369
## Spending:Learning:ESCS           -7.6590     9.7303  -0.787
## Spending:Learning:ATTLNACT       -5.6119     9.1875  -0.611
## Spending:ESCS:ATTLNACT            2.8106     6.6926   0.420
## Learning:ESCS:ATTLNACT          -13.8375     7.7212  -1.792
## Spending:Learning:ESCS:ATTLNACT -17.3835     9.5598  -1.818</code></pre>
<pre><code>## 
## Correlation matrix not shown by default, as p = 16 &gt; 12.
## Use print(x, correlation=TRUE)  or
##     vcov(x)        if you need it</code></pre>
<pre><code>## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular</code></pre>
<p>
 
</p>
<p>Here we can see the output from the LMM. At the top of this output we can see that there is an error telling us: <code>boundary(singular) fit: see ?isSingular</code>. Although at first this may be alarming, it is quite alright. All this is telling us is that one or more of the correlations for the random effects is very close to being 0. If we look at the correlations we can see that this is true. For the random effect of country, the interaction of Spending and Learning shows a correlation of 0.01. This error is okay so we can continue with analyzing the data.</p>
<p>If an error appeared stating that our model failed to converge however, this would be a problem. Although we would receive an output, we could not use it. There are many reasons that can cause a model to not converge properly. These include model mispessification, strong imbalances in the design, and having too few data to estimate the parameters. Although there are no generally accepted methods to dealing with this error, there are some methods that can be used. The optimizer settings for the model could be altered, the model could be simplified slightly or more data could be collected.</p>
<p>Within the output the main focus for the analysis is the fixed effects output. One major thing that you may notice here is that there are not any p-values. This is okay. The creator of the lmer function decided not to include any p-values in the output of the lmer function. The author argued that p-values could be misleading and that the use of p-values can sometimes create problems in research, so they decided that the best option would be not to include them in the output of the lmer function. Instead we just get the Estimate, Std. Error and the t-value. There are other functions however, that can give us the p-value for our results.</p>
<p>
 
</p>
</div>
<div id="section-generalized-linear-mixed-models" class="section level3">
<h3><strong>Generalized Linear Mixed Models</strong></h3>
<p>We could also fit a generalized linear mixed model to look at the data. These work in exactly the same way as a generalized linear model, in that they allow us to apply different family classes in an attempt to fit a model to data that is not normally distributed. With a generalized linear mixed model, we can take the same formula as was used in our linear mixed model, but add different family classes and link functions in an attempt to fit the data better.</p>
<p>Creating a generalized linear mixed model in R is very similar to that of creating a linear mixed model. This time however, instead of using the <code>lmer()</code> function form the <code>lme4</code> package we will use the <code>glmer()</code> function. The way fixed and random effects are added are identical between the two functions. With the <code>glmer()</code> function however, we can now specify families and link functions, just as was done with the <code>glm()</code> function.</p>
<p>In our example we will use the same model structure as in the linear mixed model by keeping the fixed and random effects the same. We will include the Gamma family with an identity link function, making it similar to what was done in the generalized linear model example in the previous section. In our code we have changed the default optimizer to the ‘bobyqa’ optimizer. Typically the default optimizer works well, however, in this case it was found that the ‘bobyqa’ optimizer helped in making the model converge.</p>
<pre class="r"><code># Use glmer to create a generalised linear mixed model
GLMM_mod &lt;- glmer(Score ~ Spending * Learning * ESCS * ATTLNACT +
# Specify the random effetcs and thier interactions
                     (1 + Spending * Learning | Country) +
                     (1 + ESCS * ATTLNACT | ID) +
                     (1 | Item),
                   data = read_data,
# sepcify the family you want to use and the link function
                   family = Gamma(identity),
# Change the optimizer used in the example
                   control = glmerControl(optimizer = c(&quot;bobyqa&quot;)))
# Get the output of the analysis
summary(GLMM_mod)</code></pre>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: Gamma  ( identity )
## Formula: Score ~ Spending * Learning * ESCS * ATTLNACT + (1 + Spending *  
##     Learning | Country) + (1 + ESCS * ATTLNACT | ID) + (1 | Item)
##    Data: read_data
## Control: glmerControl(optimizer = c(&quot;bobyqa&quot;))
## 
##      AIC      BIC   logLik deviance df.resid 
##  38595.2  38834.3 -19259.6  38519.2     3962 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.7483 -0.4918 -0.0241  0.4718  4.0718 
## 
## Random effects:
##  Groups   Name              Variance  Std.Dev. Corr             
##  ID       (Intercept)       1.688e+03 41.08551                  
##           ESCS              1.259e+01  3.54845  1.00            
##           ATTLNACT          7.637e+01  8.73900  0.05  0.05      
##           ESCS:ATTLNACT     8.966e+00  2.99434 -0.44 -0.44  0.87
##  Country  (Intercept)       0.000e+00  0.00000                  
##           Spending          3.282e+01  5.72861   NaN            
##           Learning          5.947e+00  2.43871   NaN  0.83      
##           Spending:Learning 2.701e+01  5.19689   NaN -0.66 -0.97
##  Item     (Intercept)       1.693e+00  1.30134                  
##  Residual                   5.870e-03  0.07662                  
## Number of obs: 4000, groups:  ID, 400; Country, 11; Item, 10
## 
## Fixed effects:
##                                  Estimate Std. Error t value Pr(&gt;|z|)    
## (Intercept)                     518.04221    6.80689  76.106  &lt; 2e-16 ***
## Spending                          0.75984    7.22405   0.105  0.91623    
## Learning                        -13.34087    5.63288  -2.368  0.01787 *  
## ESCS                             46.30929    5.66152   8.180 2.85e-16 ***
## ATTLNACT                         15.95109    5.48227   2.910  0.00362 ** 
## Spending:Learning                14.47299    7.11379   2.034  0.04190 *  
## Spending:ESCS                     2.94725    6.57244   0.448  0.65385    
## Learning:ESCS                    -3.96391    7.93726  -0.499  0.61749    
## Spending:ATTLNACT                 0.07002    6.74169   0.010  0.99171    
## Learning:ATTLNACT                10.02126    5.28576   1.896  0.05797 .  
## ESCS:ATTLNACT                    -6.96588    5.61035  -1.242  0.21438    
## Spending:Learning:ESCS            5.51793    6.95283   0.794  0.42741    
## Spending:Learning:ATTLNACT       10.37084    7.08707   1.463  0.14337    
## Spending:ESCS:ATTLNACT            1.46068    5.74627   0.254  0.79934    
## Learning:ESCS:ATTLNACT            2.84604    5.77196   0.493  0.62196    
## Spending:Learning:ESCS:ATTLNACT -13.45726    8.16751  -1.648  0.09942 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## 
## Correlation matrix not shown by default, as p = 16 &gt; 12.
## Use print(x, correlation=TRUE)  or
##     vcov(x)        if you need it</code></pre>
<pre><code>## optimizer (bobyqa) convergence code: 0 (OK)
## boundary (singular) fit: see ?isSingular
## maxfun &lt; 10 * length(par)^2 is not recommended.</code></pre>
<p>
 
</p>
<p>Here we can see that the output from the <code>glmer()</code> function is similar but not identical to that of the lmer output. One of the major differences that you will notice this time is the presence of p-values in the fixed effect output. With the p-values we are able to identify which main effects and interactions were significant. From this output we can see that there was a significant main effect of spending and a significant main effect of economic, social and cultural status on the scores.</p>
<p>
 
</p>
</div>
<div id="section-model-comparison-1" class="section level3">
<h3><strong>Model comparison</strong></h3>
<p>As was done with the general linear model and the generalized linear model, we can compare the generalized linear mixed model and the linear mixed model to see which of these two fit the data better. In order to do this we will again use the AIC values.</p>
<pre class="r"><code># Get the AIC for the LMM_read
LMM_AIC &lt;- AIC(LMM_mod)
LMM_AIC</code></pre>
<pre><code>## [1] 39337.46</code></pre>
<pre class="r"><code>#Get the AIC for GLMM_read 
GLMM_AIC &lt;- AIC(GLMM_mod)
GLMM_AIC</code></pre>
<pre><code>## [1] 38595.17</code></pre>
<p>
 
</p>
<p>From the output of the AIC values we can see that the AIC value for the generalized linear mixed model with the gamma family and link identity has a lower AIC value (AIC = 38739) compared to the AIC value of the linear mixed model (AIC = 39523). Since the generalized linear mixed model has a lower AIC value we can conclude that this model fits the data better. we can also compare this to the AIC values from the linear mixed model (AIC = 47481) and the generalized linear model (AIC = 47636). Again we can see that the AIC value for the generalized linear mixed model is lower than the AIC values for all the model we have created in this tutorial. We can therefore conclude that in this case, the generalized linear mixed model using the gamma family with an identity link has the best fit of the data.</p>
<p>
 
</p>
</div>
<div id="section-complex-model-exercise" class="section level3">
<h3><strong>Complex model Exercise</strong></h3>
<p><div class="panel-heading tutorial-quiz-title"><span data-i18n="text.quiz">Quiz</span></div></p>
<div class="panel panel-default">
<div data-label="quiz-1" class="tutorial-question panel-body">
<div id="quiz-1-answer_container" class="shiny-html-output"></div>
<div id="quiz-1-message_container" class="shiny-html-output"></div>
<div id="quiz-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz-2" class="tutorial-question panel-body">
<div id="quiz-2-answer_container" class="shiny-html-output"></div>
<div id="quiz-2-message_container" class="shiny-html-output"></div>
<div id="quiz-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz-3" class="tutorial-question panel-body">
<div id="quiz-3-answer_container" class="shiny-html-output"></div>
<div id="quiz-3-message_container" class="shiny-html-output"></div>
<div id="quiz-3-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz-4" class="tutorial-question panel-body">
<div id="quiz-4-answer_container" class="shiny-html-output"></div>
<div id="quiz-4-message_container" class="shiny-html-output"></div>
<div id="quiz-4-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<div class="panel panel-default">
<div data-label="quiz-5" class="tutorial-question panel-body">
<div id="quiz-5-answer_container" class="shiny-html-output"></div>
<div id="quiz-5-message_container" class="shiny-html-output"></div>
<div id="quiz-5-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>Run a Generalized linear mixed model similar to the one in the example given in this section but switch the identity link with a with a log link. Calculate the AIC of this new model and compare it to the AIC values of the previous models created throughout the tutorial.</p>
<div class="tutorial-exercise" data-label="GLMM-exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-ui-opts="1">{"engine":"r","has_checker":false,"caption":"<span data-i18n=\"text.enginecap\" data-i18n-opts=\"{&quot;engine&quot;:&quot;R&quot;}\">R Code<\/span>"}</script>
</div>
<div class="tutorial-exercise-support" data-label="GLMM-exercise-solution" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Run the glm() function and use a log link function 
GLMM_dat &lt;- glmer(Score ~ Spending * Learning * ESCS * ATTLNACT +
# Specify the random effetcs and thier interactions
                     (1 + Spending * Learning | Country) +
                     (1 + ESCS * ATTLNACT | ID) +
                     (1 | Item),
                   data = read_data,
# specify the family you want to use and the link function
                   family = Gamma(identity),
# Change the optimizer used in the example
                   control = glmerControl(optimizer = c(&quot;bobyqa&quot;)))
# Get the summary of the new model
summary(GLMM_dat)
# Find the AIC value of the model 
AIC(GLMM_dat)</code></pre>
</div>
<pre><code>## function (check_env) 
## {
##     if (is.list(check_env)) {
##         check_env &lt;- list2env(check_env)
##     }
##     user_code &lt;- check_env$.user_code
##     if (is.null(user_code)) {
##         return(legacy_graded(correct = FALSE, message = &quot;I didn&#39;t receive your code. Did you write any?&quot;))
##     }
##     solution_code &lt;- check_env$.solution_code
##     if (is.null(solution_code) || length(str2expression(solution_code)) == 
##         0) {
##         return(legacy_graded(correct = FALSE, message = &quot;No exercise solution provided. Defaulting to _incorrect_.&quot;))
##     }
##     message &lt;- code_feedback(user_code = user_code, solution_code = solution_code, 
##         env = check_env, allow_partial_matching = allow_partial_matching)
##     if (is.null(message)) {
##         return(legacy_graded(correct = TRUE, message = glue_message(glue_correct %||% 
##             gradethis_legacy_options$gradethis.glue_correct, 
##             .is_correct = TRUE, .message = NULL, .correct = correct, 
##             .user_code = user_code)))
##     }
##     message &lt;- glue_message(glue_incorrect %||% gradethis_legacy_options$gradethis.glue_incorrect, 
##         .is_correct = FALSE, .message = message, .incorrect = incorrect, 
##         .user_code = user_code)
##     legacy_graded(correct = FALSE, message = message)
## }
## &lt;bytecode: 0x7fefd874ea88&gt;
## &lt;environment: 0x7fefd8752350&gt;</code></pre>
<p>
 
</p>
</div>
<div id="section-conclusion" class="section level3">
<h3><strong>Conclusion</strong></h3>
<p>In this tutorial we have covered how to sort data for analysis and how to run different types of models. Now that you have completed this tutorial you should have a basic understanding of: how to sort data for analysis, how to run linear models and generalized linear models, the basic components behind linear mixed models and generalized linear mixed models, how to run linear mixed models and generalized linear mixed models, how to compare models.</p>
We hope this tutorial has helped you to understand how generalized linear mixed models work and how to use them in your data analysis.
<p>
 
</p>
</div>
</div>
<div id="section-coding-exercises" class="section level2">
<h2>Coding exercises</h2>
<p>In this section you can practice what you have learned in the tutorial. Here we would like you to firslty create a generalised linear model which fits the PISA data, using the same independent and dependent variables as were used in the tutorial. This time however we would like you to use a gamma family argumetn with a log link function. Once you have completed that we would like you to greate a Generalised linear Mixed model using the same independent and dependent variables as were used in the tutorial but use a gamma family argumetn with a log link function.</p>
<div id="section-glm-exercise" class="section level3">
<h3><strong>Glm exercise</strong></h3>
Create a generalized linear model similar to the one used in the tutorial. This time however, use a log link function. Once you have created the model with the log link function, calculate the AIC value.
<div class="tutorial-exercise" data-label="coding1-exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-ui-opts="1">{"engine":"r","has_checker":false,"caption":"<span data-i18n=\"text.enginecap\" data-i18n-opts=\"{&quot;engine&quot;:&quot;R&quot;}\">R Code<\/span>"}</script>
</div>
<div class="tutorial-exercise-support" data-label="coding1-exercise-solution" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Run the glm() function and use a log link function 
GLM_dat &lt;- glm(Score ~ Spending * Learning * ESCS * ATTLNACT + Item, data = read_data, family= Gamma(link = &quot;log&quot;))
# Get the summary of the new model
summary(GLM_dat)
# Find the AIC value of the model 
AIC(GLM_dat)</code></pre>
</div>
</div>
<div id="section-glmm-exercise" class="section level3">
<h3><strong>GLMM exercise</strong></h3>
<p>Run a Generalized linear mixed model similar to the one in the example given in this section but switch the identity link with a with a log link. Calculate the AIC of this new model and compare it to the AIC values of the previous models created throughout the tutorial.</p>
<div class="tutorial-exercise" data-label="coding2-exercise" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-ui-opts="1">{"engine":"r","has_checker":false,"caption":"<span data-i18n=\"text.enginecap\" data-i18n-opts=\"{&quot;engine&quot;:&quot;R&quot;}\">R Code<\/span>"}</script>
</div>
<div class="tutorial-exercise-support" data-label="coding2-exercise-solution" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Run the glm() function and use a log link function 
GLMM_dat &lt;- glmer(Score ~ Spending * Learning * ESCS * ATTLNACT +
# Specify the random effetcs and thier interactions
                     (1 + Spending * Learning | Country) +
                     (1 + ESCS * ATTLNACT | ID) +
                     (1 | Item),
                   data = read_data,
# sepcify the family you want to use and the link function
                   family = Gamma(identity),
# Change the optimizer used in the example
                   control = glmerControl(optimizer = c(&quot;bobyqa&quot;)))
# Get the summary of the new model
summary(GLMM_dat)
# Find the AIC value of the model 
AIC(GLMM_dat)</code></pre>
</div>
<p>
 
</p>
<p>
 
</p>

<script type="application/shiny-prerendered" data-context="server-start">
knitr::opts_chunk$set(echo = FALSE)

library(learnr)
library(tidyverse)
library(gradethis)
library(rcompanion)
library(lme4)

### INSTALLING LEARNR AND GRADETHIS FROM GITHUB ###
#devtools::install_github("rstudio/learnr")
#devtools::install_github("rstudio-education/gradethis")

library(gradethis) #quiz/exercise questions
gradethis_setup() #quiz/exercise questions

load("GLM.RData")
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::clear_exercise_cache_env()
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::event_trigger(session, "session_stop")
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_setup_chunk("__setup__", c("knitr::opts_chunk$set(echo = FALSE)", "", "library(learnr)", 
"library(tidyverse)", "library(gradethis)", "library(rcompanion)", 
"library(lme4)", "", "### INSTALLING LEARNR AND GRADETHIS FROM GITHUB ###", 
"#devtools::install_github(\"rstudio/learnr\")", "#devtools::install_github(\"rstudio-education/gradethis\")", 
"", "library(gradethis) #quiz/exercise questions", "gradethis_setup() #quiz/exercise questions", 
"", "load(\"GLM.RData\")"), overwrite = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_setup_chunk("__setup__", c("knitr::opts_chunk$set(echo = FALSE)", "", "library(learnr)", 
"library(tidyverse)", "library(gradethis)", "library(rcompanion)", 
"library(lme4)", "", "### INSTALLING LEARNR AND GRADETHIS FROM GITHUB ###", 
"#devtools::install_github(\"rstudio/learnr\")", "#devtools::install_github(\"rstudio-education/gradethis\")", 
"", "library(gradethis) #quiz/exercise questions", "gradethis_setup() #quiz/exercise questions", 
"", "load(\"GLM.RData\")"), overwrite = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_setup_chunk("__setup__", c("knitr::opts_chunk$set(echo = FALSE)", "", "library(learnr)", 
"library(tidyverse)", "library(gradethis)", "library(rcompanion)", 
"library(lme4)", "", "### INSTALLING LEARNR AND GRADETHIS FROM GITHUB ###", 
"#devtools::install_github(\"rstudio/learnr\")", "#devtools::install_github(\"rstudio-education/gradethis\")", 
"", "library(gradethis) #quiz/exercise questions", "gradethis_setup() #quiz/exercise questions", 
"", "load(\"GLM.RData\")"), overwrite = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_setup_chunk("__setup__", c("knitr::opts_chunk$set(echo = FALSE)", "", "library(learnr)", 
"library(tidyverse)", "library(gradethis)", "library(rcompanion)", 
"library(lme4)", "", "### INSTALLING LEARNR AND GRADETHIS FROM GITHUB ###", 
"#devtools::install_github(\"rstudio/learnr\")", "#devtools::install_github(\"rstudio-education/gradethis\")", 
"", "library(gradethis) #quiz/exercise questions", "gradethis_setup() #quiz/exercise questions", 
"", "load(\"GLM.RData\")"), overwrite = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_checkbox", label = "sorting_exercise-1", 
    question = structure("What happens when we standardize the data? (Select 2)", html = TRUE, class = c("html", 
    "character")), answers = list(structure(list(id = "lnr_ans_65f5934", 
        option = "It transforms our data into standard units", 
        value = "It transforms our data into standard units", 
        label = structure("It transforms our data into standard units", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_4ddd76c", 
        option = "It keeps our data tidy", value = "It keeps our data tidy", 
        label = structure("It keeps our data tidy", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_284bb90", 
        option = "It makes our data harder to compare throughout the analysis", 
        value = "It makes our data harder to compare throughout the analysis", 
        label = structure("It makes our data harder to compare throughout the analysis", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a90ade1", 
        option = "It makes our data easier to compare throughout the analysis", 
        value = "It makes our data easier to compare throughout the analysis", 
        label = structure("It makes our data easier to compare throughout the analysis", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
    "character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
    "character"))), messages = list(correct = structure("Correct! When we standardize data we transform the data points into standard units. This allows us to create internal consistency between variable that are initial measured on different scales, making them easier to compare throughout the experiment", html = TRUE, class = c("html", 
    "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), message = NULL, post_message = NULL), ids = list(
        answer = "sorting_exercise-1-answer", question = "sorting_exercise-1"), 
    loading = structure("<strong>Loading:<\u002fstrong> \nWhat happens when we standardize the data? (Select 2)\n<br/><br/><br/>", html = TRUE, class = c("html", 
    "character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1718262675.69987, options = list()), class = c("learnr_checkbox", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "sorting_exercise-2", 
    question = structure("What function can be used to standardize the data?", html = TRUE, class = c("html", 
    "character")), answers = list(structure(list(id = "lnr_ans_182fb60", 
        option = "standardize()", value = "standardize()", label = structure("standardize()", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_8c281a4", 
        option = "std()", value = "std()", label = structure("std()", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a0cb6cb", 
        option = "scale()", value = "scale()", label = structure("scale()", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_581f756", 
        option = "transform()", value = "transform()", label = structure("transform()", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
    "character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
    "character"))), messages = list(correct = structure("Correct! The scale() function is used to standardize the data", html = TRUE, class = c("html", 
    "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), message = NULL, post_message = NULL), ids = list(
        answer = "sorting_exercise-2-answer", question = "sorting_exercise-2"), 
    loading = structure("<strong>Loading:<\u002fstrong> \nWhat function can be used to standardize the data?\n<br/><br/><br/>", html = TRUE, class = c("html", 
    "character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1251881934.41705, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "LM_Questions-1", 
    question = structure("What does the family argument relate to?", html = TRUE, class = c("html", 
    "character")), answers = list(structure(list(id = "lnr_ans_559f00b", 
        option = "The type of optimizer used", value = "The type of optimizer used", 
        label = structure("The type of optimizer used", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_deb1c6a", 
        option = "The distribution of the independent variable", 
        value = "The distribution of the independent variable", 
        label = structure("The distribution of the independent variable", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_c3183ea", 
        option = "The distribution of the dependent variable", 
        value = "The distribution of the dependent variable", 
        label = structure("The distribution of the dependent variable", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_2151966", 
        option = "The type of optimizer we want to use", value = "The type of optimizer we want to use", 
        label = structure("The type of optimizer we want to use", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
    "character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
    "character"))), messages = list(correct = structure("Correct! The family argument lets us add different family classes relating to the distribution of our dependent variable, i.e. The family argument relates to the distribution of the thing we are trying to predict", html = TRUE, class = c("html", 
    "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), message = NULL, post_message = NULL), ids = list(
        answer = "LM_Questions-1-answer", question = "LM_Questions-1"), 
    loading = structure("<strong>Loading:<\u002fstrong> \nWhat does the family argument relate to?\n<br/><br/><br/>", html = TRUE, class = c("html", 
    "character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1664602514.72486, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "LM_Questions-2", 
    question = structure("What does the link function do?", html = TRUE, class = c("html", 
    "character")), answers = list(structure(list(id = "lnr_ans_8e7d3eb", 
        option = "Applies a transformation to the model parameters", 
        value = "Applies a transformation to the model parameters", 
        label = structure("Applies a transformation to the model parameters", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_4065c5b", 
        option = "Transforms the data", value = "Transforms the data", 
        label = structure("Transforms the data", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a16397", 
        option = "Makes the model fit better", value = "Makes the model fit better", 
        label = structure("Makes the model fit better", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ae80eca", 
        option = "Allows us to deal with different distributions of data", 
        value = "Allows us to deal with different distributions of data", 
        label = structure("Allows us to deal with different distributions of data", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
    "character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
    "character"))), messages = list(correct = structure("Correct! Using link functions allows us to transform the model parameters.", html = TRUE, class = c("html", 
    "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), message = NULL, post_message = NULL), ids = list(
        answer = "LM_Questions-2-answer", question = "LM_Questions-2"), 
    loading = structure("<strong>Loading:<\u002fstrong> \nWhat does the link function do?\n<br/><br/><br/>", html = TRUE, class = c("html", 
    "character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 2101977178.02119, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "LM_Questions-3", 
    question = structure("True or False: When comparing two models using AIC values, the model with the highest AIC fits the data better", html = TRUE, class = c("html", 
    "character")), answers = list(structure(list(id = "lnr_ans_172445f", 
        option = "True", value = "True", label = structure("True", html = TRUE, class = c("html", 
        "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer")), structure(list(id = "lnr_ans_9b63932", 
        option = "False", value = "False", label = structure("False", html = TRUE, class = c("html", 
        "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
    "tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
    "character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
    "character"))), messages = list(correct = structure("Correct! The lower the AIC value, the better a model fits the data", html = TRUE, class = c("html", 
    "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
    "character")), message = NULL, post_message = NULL), ids = list(
        answer = "LM_Questions-3-answer", question = "LM_Questions-3"), 
    loading = structure("<strong>Loading:<\u002fstrong> \nTrue or False: When comparing two models using AIC values, the model with the highest AIC fits the data better\n<br/><br/><br/>", html = TRUE, class = c("html", 
    "character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1530219985.28744, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-1", question = structure("What is a fixed effect?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_a6417ac", 
    option = "A dependent variable that is assumed to change when the experiment is replicated", 
    value = "A dependent variable that is assumed to change when the experiment is replicated", 
    label = structure("A dependent variable that is assumed to change when the experiment is replicated", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_720cfa9", 
    option = "A predictor variable that is assumed to remain constant when the experiment is replicated", 
    value = "A predictor variable that is assumed to remain constant when the experiment is replicated", 
    label = structure("A predictor variable that is assumed to remain constant when the experiment is replicated", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_83fe5d0", 
    option = " A predictor variable that is assumed to change when the experiment is replicated", 
    value = " A predictor variable that is assumed to change when the experiment is replicated", 
    label = structure("A predictor variable that is assumed to change when the experiment is replicated", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_d092cb8", 
    option = "A dependent variable that is assumed to remain constant when the experiment is replicated", 
    value = "A dependent variable that is assumed to remain constant when the experiment is replicated", 
    label = structure("A dependent variable that is assumed to remain constant when the experiment is replicated", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct! A fixed effect is a predictor variable that is assumed to remain constant when the experiment is replicated. These are typically the predictor variables of interest in our model", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz-1-answer", question = "quiz-1"), loading = structure("<strong>Loading:<\u002fstrong> \nWhat is a fixed effect?\n<br/><br/><br/>", html = TRUE, class = c("html", 
"character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1274587439.40647, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-2", question = structure("What is the purpose of adding a random slope?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_8cea81b", 
    option = "It allows us to fit slopes to account for the variance of random effects", 
    value = "It allows us to fit slopes to account for the variance of random effects", 
    label = structure("It allows us to fit slopes to account for the variance of random effects", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_fe6be92", 
    option = "It allows us to fit slopes to account for the variance of fixed effects", 
    value = "It allows us to fit slopes to account for the variance of fixed effects", 
    label = structure("It allows us to fit slopes to account for the variance of fixed effects", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_63c9bc", 
    option = "It allows us to see the interaction between random effects", 
    value = "It allows us to see the interaction between random effects", 
    label = structure("It allows us to see the interaction between random effects", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_74e6266", 
    option = "It allows us to see the interaction between the fixed factors and random effects", 
    value = "It allows us to see the interaction between the fixed factors and random effects", 
    label = structure("It allows us to see the interaction between the fixed factors and random effects", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct! BY adding random slopes we can account for the variance of the random factors", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz-2-answer", question = "quiz-2"), loading = structure("<strong>Loading:<\u002fstrong> \nWhat is the purpose of adding a random slope?\n<br/><br/><br/>", html = TRUE, class = c("html", 
"character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1540956020.28244, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-3", question = structure("Which package contains functions for running a linear mixed model?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_3fe2754", 
    option = "base", value = "base", label = structure("base", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_af4c139", 
    option = "stats", value = "stats", label = structure("stats", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_4c914b8", 
    option = "lme4", value = "lme4", label = structure("lme4", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_300b7ff", 
    option = "car", value = "car", label = structure("car", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct! The lme4 package can be used to run both linear mixed models and generalized linear mixed models", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz-3-answer", question = "quiz-3"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich package contains functions for running a linear mixed model?\n<br/><br/><br/>", html = TRUE, class = c("html", 
"character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1894759212.61768, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-4", question = structure("Which function is used to run a generalized linear mixed model?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_aeed247", 
    option = "lm", value = "lm", label = structure("lm", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_8b34187", 
    option = "lmer", value = "lmer", label = structure("lmer", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_4dc2e44", 
    option = "glm", value = "glm", label = structure("glm", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_355db23", 
    option = "glmer", value = "glmer", label = structure("glmer", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct! the glmer function is used to create a generalized linear mixed model", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz-4-answer", question = "quiz-4"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich function is used to run a generalized linear mixed model?\n<br/><br/><br/>", html = TRUE, class = c("html", 
"character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 1674416267.72029, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-5", question = structure("Which of these is NOT a reason that a model may fail to converge?", html = TRUE, class = c("html", 
"character")), answers = list(structure(list(id = "lnr_ans_e6e517f", 
    option = "The model parameters were misspecified", value = "The model parameters were misspecified", 
    label = structure("The model parameters were misspecified", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_af9ad9a", 
    option = "The data set is too large for R to fit the model", 
    value = "The data set is too large for R to fit the model", 
    label = structure("The data set is too large for R to fit the model", html = TRUE, class = c("html", 
    "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_66b9751", 
    option = "There are strong imbalances in the design", value = "There are strong imbalances in the design", 
    label = structure("There are strong imbalances in the design", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer")), structure(list(id = "lnr_ans_69800b9", 
    option = "There are too few data points", value = "There are too few data points", 
    label = structure("There are too few data points", html = TRUE, class = c("html", 
    "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", 
"tutorial_quiz_answer"))), button_labels = list(submit = structure("<span data-i18n=\"button.questionsubmit\">Submit Answer<\u002fspan>", html = TRUE, class = c("html", 
"character")), try_again = structure("<span data-i18n=\"button.questiontryagain\">Try Again<\u002fspan>", html = TRUE, class = c("html", 
"character"))), messages = list(correct = structure("Correct! there are many reasons that a model fails to converge however, having too many data points is not one of them!", html = TRUE, class = c("html", 
"character")), try_again = structure("Incorrect", html = TRUE, class = c("html", 
"character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", 
"character")), message = NULL, post_message = NULL), ids = list(
    answer = "quiz-5-answer", question = "quiz-5"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich of these is NOT a reason that a model may fail to converge?\n<br/><br/><br/>", html = TRUE, class = c("html", 
"character")), random_answer_order = FALSE, allow_retry = TRUE, 
    seed = 229289522.393229, options = list()), class = c("learnr_radio", 
"tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-GLMM-exercise-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-GLMM-exercise-code-editor`)), session)
output$`tutorial-exercise-GLMM-exercise-output` <- renderUI({
  `tutorial-exercise-GLMM-exercise-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_cache("GLMM-exercise", list(setup = NULL, chunks = list(list(label = "GLMM-exercise", 
    code = "", opts = list(label = "\"GLMM-exercise\"", exercise = "TRUE", 
        exercise.eval = "TRUE"), engine = "r")), code_check = NULL, 
    error_check = NULL, check = NULL, solution = structure(c("# Run the glm() function and use a log link function ", 
    "GLMM_dat <- glmer(Score ~ Spending * Learning * ESCS * ATTLNACT +", 
    "# Specify the random effetcs and thier interactions", "                     (1 + Spending * Learning | Country) +", 
    "                     (1 + ESCS * ATTLNACT | ID) +", "                     (1 | Item),", 
    "                   data = read_data,", "# specify the family you want to use and the link function", 
    "                   family = Gamma(identity),", "# Change the optimizer used in the example", 
    "                   control = glmerControl(optimizer = c(\"bobyqa\")))", 
    "# Get the summary of the new model", "summary(GLMM_dat)", 
    "# Find the AIC value of the model ", "AIC(GLMM_dat)"), chunk_opts = list(
        label = "GLMM-exercise-solution")), options = list(eval = TRUE, 
        echo = TRUE, results = "markup", tidy = FALSE, tidy.opts = NULL, 
        collapse = FALSE, prompt = FALSE, comment = NA, highlight = FALSE, 
        strip.white = TRUE, size = "normalsize", background = "#F7F7F7", 
        cache = 0, cache.path = "GLM_Tutorial_cache/html/", cache.vars = NULL, 
        cache.lazy = TRUE, dependson = NULL, autodep = FALSE, 
        cache.rebuild = FALSE, fig.keep = "high", fig.show = "asis", 
        fig.align = "default", fig.path = "GLM_Tutorial_files/figure-html/", 
        dev = "png", dev.args = NULL, dpi = 192, fig.ext = "png", 
        fig.width = 6.5, fig.height = 4, fig.env = "figure", 
        fig.cap = NULL, fig.scap = NULL, fig.lp = "fig:", fig.subcap = NULL, 
        fig.pos = "", out.width = 624, out.height = NULL, out.extra = NULL, 
        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, 
        aniopts = "controls,loop", warning = TRUE, error = FALSE, 
        message = TRUE, render = NULL, ref.label = NULL, child = NULL, 
        engine = "r", split = FALSE, include = TRUE, purl = TRUE, 
        max.print = 1000, tutorial = TRUE, exercise.timelimit = 60, 
        exercise.checker = "function (label = NULL, solution_code = NULL, user_code = NULL, \n    check_code = NULL, envir_result = NULL, evaluate_result = NULL, \n    envir_prep = NULL, last_value = NULL, ...) \n{\n    (utils::getFromNamespace(\"check_exercise\", \"gradethis\"))(label = label, \n        solution_code = solution_code, user_code = user_code, \n        check_code = check_code, envir_result = envir_result, \n        evaluate_result = evaluate_result, envir_prep = envir_prep, \n        last_value = last_value, ...)\n}", 
        exercise.error.check.code = "gradethis_error_checker()", 
        label = "GLMM-exercise", exercise = TRUE, exercise.eval = TRUE, 
        code = "", out.width.px = 624, out.height.px = 384, params.src = "GLMM-exercise, exercise = TRUE, exercise.eval = TRUE", 
        fig.alt = NULL, fig.num = 0L, exercise.df_print = "paged"), 
    engine = "r"))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-coding1-exercise-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-coding1-exercise-code-editor`)), session)
output$`tutorial-exercise-coding1-exercise-output` <- renderUI({
  `tutorial-exercise-coding1-exercise-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_cache("coding1-exercise", list(setup = NULL, chunks = list(list(label = "coding1-exercise", 
    code = "", opts = list(label = "\"coding1-exercise\"", exercise = "TRUE", 
        exercise.eval = "TRUE"), engine = "r")), code_check = NULL, 
    error_check = NULL, check = NULL, solution = structure(c("# Run the glm() function and use a log link function ", 
    "GLM_dat <- glm(Score ~ Spending * Learning * ESCS * ATTLNACT + Item, data = read_data, family= Gamma(link = \"log\"))", 
    "# Get the summary of the new model", "summary(GLM_dat)", 
    "# Find the AIC value of the model ", "AIC(GLM_dat)"), chunk_opts = list(
        label = "coding1-exercise-solution")), options = list(
        eval = TRUE, echo = TRUE, results = "markup", tidy = FALSE, 
        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, 
        highlight = FALSE, strip.white = TRUE, size = "normalsize", 
        background = "#F7F7F7", cache = 0, cache.path = "GLM_Tutorial_cache/html/", 
        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, 
        autodep = FALSE, cache.rebuild = FALSE, fig.keep = "high", 
        fig.show = "asis", fig.align = "default", fig.path = "GLM_Tutorial_files/figure-html/", 
        dev = "png", dev.args = NULL, dpi = 192, fig.ext = "png", 
        fig.width = 6.5, fig.height = 4, fig.env = "figure", 
        fig.cap = NULL, fig.scap = NULL, fig.lp = "fig:", fig.subcap = NULL, 
        fig.pos = "", out.width = 624, out.height = NULL, out.extra = NULL, 
        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, 
        aniopts = "controls,loop", warning = TRUE, error = FALSE, 
        message = TRUE, render = NULL, ref.label = NULL, child = NULL, 
        engine = "r", split = FALSE, include = TRUE, purl = TRUE, 
        max.print = 1000, tutorial = TRUE, exercise.timelimit = 60, 
        exercise.checker = "function (label = NULL, solution_code = NULL, user_code = NULL, \n    check_code = NULL, envir_result = NULL, evaluate_result = NULL, \n    envir_prep = NULL, last_value = NULL, ...) \n{\n    (utils::getFromNamespace(\"check_exercise\", \"gradethis\"))(label = label, \n        solution_code = solution_code, user_code = user_code, \n        check_code = check_code, envir_result = envir_result, \n        evaluate_result = evaluate_result, envir_prep = envir_prep, \n        last_value = last_value, ...)\n}", 
        exercise.error.check.code = "gradethis_error_checker()", 
        label = "coding1-exercise", exercise = TRUE, exercise.eval = TRUE, 
        code = "", out.width.px = 624, out.height.px = 384, params.src = "coding1-exercise, exercise = TRUE, exercise.eval = TRUE", 
        fig.alt = NULL, fig.num = 0L, exercise.df_print = "paged"), 
    engine = "r"))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-coding2-exercise-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-coding2-exercise-code-editor`)), session)
output$`tutorial-exercise-coding2-exercise-output` <- renderUI({
  `tutorial-exercise-coding2-exercise-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::store_exercise_cache("coding2-exercise", list(setup = NULL, chunks = list(list(label = "coding2-exercise", 
    code = "", opts = list(label = "\"coding2-exercise\"", exercise = "TRUE", 
        exercise.eval = "TRUE"), engine = "r")), code_check = NULL, 
    error_check = NULL, check = NULL, solution = structure(c("# Run the glm() function and use a log link function ", 
    "GLMM_dat <- glmer(Score ~ Spending * Learning * ESCS * ATTLNACT +", 
    "# Specify the random effetcs and thier interactions", "                     (1 + Spending * Learning | Country) +", 
    "                     (1 + ESCS * ATTLNACT | ID) +", "                     (1 | Item),", 
    "                   data = read_data,", "# sepcify the family you want to use and the link function", 
    "                   family = Gamma(identity),", "# Change the optimizer used in the example", 
    "                   control = glmerControl(optimizer = c(\"bobyqa\")))", 
    "# Get the summary of the new model", "summary(GLMM_dat)", 
    "# Find the AIC value of the model ", "AIC(GLMM_dat)"), chunk_opts = list(
        label = "coding2-exercise-solution")), options = list(
        eval = TRUE, echo = TRUE, results = "markup", tidy = FALSE, 
        tidy.opts = NULL, collapse = FALSE, prompt = FALSE, comment = NA, 
        highlight = FALSE, strip.white = TRUE, size = "normalsize", 
        background = "#F7F7F7", cache = 0, cache.path = "GLM_Tutorial_cache/html/", 
        cache.vars = NULL, cache.lazy = TRUE, dependson = NULL, 
        autodep = FALSE, cache.rebuild = FALSE, fig.keep = "high", 
        fig.show = "asis", fig.align = "default", fig.path = "GLM_Tutorial_files/figure-html/", 
        dev = "png", dev.args = NULL, dpi = 192, fig.ext = "png", 
        fig.width = 6.5, fig.height = 4, fig.env = "figure", 
        fig.cap = NULL, fig.scap = NULL, fig.lp = "fig:", fig.subcap = NULL, 
        fig.pos = "", out.width = 624, out.height = NULL, out.extra = NULL, 
        fig.retina = 2, external = TRUE, sanitize = FALSE, interval = 1, 
        aniopts = "controls,loop", warning = TRUE, error = FALSE, 
        message = TRUE, render = NULL, ref.label = NULL, child = NULL, 
        engine = "r", split = FALSE, include = TRUE, purl = TRUE, 
        max.print = 1000, tutorial = TRUE, exercise.timelimit = 60, 
        exercise.checker = "function (label = NULL, solution_code = NULL, user_code = NULL, \n    check_code = NULL, envir_result = NULL, evaluate_result = NULL, \n    envir_prep = NULL, last_value = NULL, ...) \n{\n    (utils::getFromNamespace(\"check_exercise\", \"gradethis\"))(label = label, \n        solution_code = solution_code, user_code = user_code, \n        check_code = check_code, envir_result = envir_result, \n        evaluate_result = evaluate_result, envir_prep = envir_prep, \n        last_value = last_value, ...)\n}", 
        exercise.error.check.code = "gradethis_error_checker()", 
        label = "coding2-exercise", exercise = TRUE, exercise.eval = TRUE, 
        code = "", out.width.px = 624, out.height.px = 384, params.src = "coding2-exercise, exercise = TRUE, exercise.eval = TRUE", 
        fig.alt = NULL, fig.num = 0L, exercise.df_print = "paged"), 
    engine = "r"))
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["i18n"]},{"type":"character","attributes":{},"value":["1.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/i18n"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["i18next.min.js","tutorial-i18n-init.js"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["<script id=\"i18n-cstm-trns\" type=\"application/json\">{\"language\":\"en\",\"resources\":{\"en\":{\"translation\":{\"button\":{\"runcode\":\"Run Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Hint\",\"hint_plural\":\"Hints\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Next Hint\",\"hintprev\":\"Previous Hint\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copy to Clipboard\",\"startover\":\"Start Over\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continue\",\"submitanswer\":\"Submit Answer\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Previous Topic\",\"nexttopic\":\"Next Topic\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Try Again\"},\"text\":{\"startover\":\"Start Over\",\"areyousure\":\"Are you sure you want to start over? (all exercise progress will be reset)\",\"youmustcomplete\":\"You must complete the\",\"exercise\":\"exercise\",\"exercise_plural\":\"exercises\",\"inthissection\":\"in this section before continuing.\",\"code\":\"Code\",\"enginecap\":\"{{engine}} $t(text.code)\",\"quiz\":\"Quiz\"}}},\"fr\":{\"translation\":{\"button\":{\"runcode\":\"Lancer le Code\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Indication\",\"hint_plural\":\"Indications\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Indication Suivante\",\"hintprev\":\"Indication Précédente\",\"solution\":\"Solution\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copier dans le Presse-papier\",\"startover\":\"Recommencer\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuer\",\"submitanswer\":\"Soumettre\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Chapitre Précédent\",\"nexttopic\":\"Chapitre Suivant\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Réessayer\"},\"text\":{\"startover\":\"Recommencer\",\"areyousure\":\"Êtes-vous certains de vouloir recommencer? (La progression sera remise à zéro)\",\"youmustcomplete\":\"Vous devez d'abord compléter\",\"exercise\":\"l'exercice\",\"exercise_plural\":\"des exercices\",\"inthissection\":\"de cette section avec de continuer.\",\"code\":\"Code\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\"}}},\"es\":{\"translation\":{\"button\":{\"runcode\":\"Ejecutar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Pista\",\"hint_plural\":\"Pistas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Siguiente pista\",\"hintprev\":\"Pista anterior\",\"solution\":\"Solución\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar al portapapeles\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar respuesta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tema anterior\",\"nexttopic\":\"Tema siguiente\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Volver a intentar\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"¿De verdad quieres empezar de nuevo? (todo el progreso del ejercicio se perderá)\",\"youmustcomplete\":\"Debes completar\",\"exercise\":\"el ejercicio\",\"exercise_plural\":\"los ejercicios\",\"inthissection\":\"en esta sección antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Cuestionario\"}}},\"pt\":{\"translation\":{\"button\":{\"runcode\":\"Executar código\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Dica\",\"hint_plural\":\"Dicas\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Próxima dica\",\"hintprev\":\"Dica anterior\",\"solution\":\"Solução\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Copiar para a área de transferência\",\"startover\":\"Reiniciar\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Continuar\",\"submitanswer\":\"Enviar resposta\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Tópico anterior\",\"nexttopic\":\"Próximo tópico\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tentar novamente\"},\"text\":{\"startover\":\"Reiniciar\",\"areyousure\":\"Tem certeza que deseja começar novamente? (todo o progresso feito será perdido)\",\"youmustcomplete\":\"Você deve completar\",\"exercise\":\"o exercício\",\"exercise_plural\":\"os exercícios\",\"inthissection\":\"nesta seção antes de continuar.\",\"code\":\"Código\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Quiz\"}}},\"tr\":{\"translation\":{\"button\":{\"runcode\":\"Çalıştırma Kodu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Ipucu\",\"hint_plural\":\"İpuçları\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Sonraki İpucu\",\"hintprev\":\"Önceki İpucu\",\"solution\":\"Çözüm\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Pano'ya Kopyala\",\"startover\":\"Baştan Başlamak\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Devam et\",\"submitanswer\":\"Cevabı onayla\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Önceki Konu\",\"nexttopic\":\"Sonraki Konu\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Tekrar Deneyin\"},\"text\":{\"startover\":\"Baştan Başlamak\",\"areyousure\":\"Baştan başlamak istediğinizden emin misiniz? (tüm egzersiz ilerlemesi kaybolacak)\",\"youmustcomplete\":\"Tamamlamalısın\",\"exercise\":\"egzersiz\",\"exercise_plural\":\"egzersizler\",\"inthissection\":\"devam etmeden önce bu bölümde\",\"code\":\"Kod\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Sınav\"}}},\"emo\":{\"translation\":{\"button\":{\"runcode\":\"🏃\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"💡\",\"hint_plural\":\"$t(button.hint)\",\"hinttitle\":\"$t(button.hint)\",\"solution\":\"🎯\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"📋\",\"startover\":\"⏮\",\"startovertitle\":\"Start Over\",\"continue\":\"✅\",\"submitanswer\":\"🆗\",\"submitanswertitle\":\"Submit Answer\",\"previoustopic\":\"⬅\",\"nexttopic\":\"➡\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"🔁\"},\"text\":{\"startover\":\"⏮\",\"areyousure\":\"🤔\",\"youmustcomplete\":\"⚠️ 👉 🧑‍💻\",\"exercise\":\"\",\"exercise_plural\":\"\",\"inthissection\":\"\",\"code\":\"💻\",\"enginecap\":\"$t(text.code) {{engine}}\"}}},\"eu\":{\"translation\":{\"button\":{\"runcode\":\"Kodea egikaritu\",\"runcodetitle\":\"$t(button.runcode) ({{kbd}})\",\"hint\":\"Laguntza\",\"hint_plural\":\"Laguntza\",\"hinttitle\":\"$t(button.hint)\",\"hintnext\":\"Aurreko laguntza\",\"hintprev\":\"Hurrengo laguntza\",\"solution\":\"Ebazpena\",\"solutiontitle\":\"$t(button.solution)\",\"copyclipboard\":\"Arbelean kopiatu\",\"startover\":\"Berrabiarazi\",\"startovertitle\":\"$t(button.startover)\",\"continue\":\"Jarraitu\",\"submitanswer\":\"Erantzuna bidali\",\"submitanswertitle\":\"$t(button.submitanswer)\",\"previoustopic\":\"Aurreko atala\",\"nexttopic\":\"Hurrengo atala\",\"questionsubmit\":\"$t(button.submitanswer)\",\"questiontryagain\":\"Berriro saiatu\"},\"text\":{\"startover\":\"Berrabiarazi\",\"areyousure\":\"Berriro hasi nahi duzu? (egindako lana galdu egingo da)\",\"youmustcomplete\":\"Aurrera egin baino lehen atal honetako\",\"exercise\":\"ariketa egin behar duzu.\",\"exercise_plural\":\"ariketak egin behar dituzu.\",\"inthissection\":\"\",\"code\":\"Kodea\",\"enginecap\":\"$t(text.code) {{engine}}\",\"quiz\":\"Galdetegia\"}}}}}<\/script>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.7"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1.9008"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1.9008"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117]}},"value":[{"type":"character","attributes":{},"value":["assertthat","backports","base","boot","broom","bslib","cellranger","checkmate","cli","codetools","coin","colorspace","compiler","crayon","curl","datasets","DBI","dbplyr","DescTools","digest","dplyr","ellipsis","EMT","evaluate","expm","fansi","farver","fastmap","forcats","fs","generics","ggplot2","glue","gradethis","graphics","grDevices","grid","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","httr","jquerylib","jsonlite","knitr","labeling","later","lattice","learnr","libcoin","lifecycle","lme4","lmtest","lubridate","magrittr","markdown","MASS","Matrix","matrixStats","methods","mime","minqa","modelr","modeltools","multcomp","multcompView","munsell","mvtnorm","nlme","nloptr","nortest","parallel","pillar","pkgconfig","plyr","promises","purrr","R6","rcompanion","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","sandwich","sass","scales","shiny","splines","statmod","stats","stats4","stringi","stringr","survival","TH.data","tibble","tidyr","tidyselect","tidyverse","tools","utf8","utils","vctrs","withr","xfun","xml2","xtable","yaml","zoo"]},{"type":"character","attributes":{},"value":["0.2.1","1.2.1","3.6.1","1.3-22","0.7.6","0.2.4","1.1.0","2.0.0","2.4.0","0.2-16","1.3-1","1.4-1","3.6.1","1.4.1","4.3","3.6.1","1.1.0","2.1.1","0.99.34","0.6.27","1.0.5","0.3.1","1.1","0.14","0.999-4","0.4.2","2.0.3","1.1.0","0.5.1","1.5.0","0.0.2","3.3.3","1.4.2","0.2.3.9001","3.6.1","3.6.1","3.6.1","0.3.0","2.4.0","0.8","1.0.0","0.5.1.1","1.5.3","1.5.5","1.4.2","0.1.3","1.7.2","1.32","0.3","1.1.0.1","0.20-38","0.10.1.9008","1.0-5","1.0.0","1.1-26","0.9-37","1.7.10","2.0.1","1.1","7.3-51.4","1.2-17","0.56.0","3.6.1","0.10","1.2.4","0.1.8","0.2-23","1.4-13","0.1-8","0.5.0","1.1-0","3.1-140","1.2.2.1","1.0-4","3.6.1","1.6.0","2.0.3","1.8.6","1.2.0.1","0.3.4","2.5.0","2.3.25","1.0.6","1.4.0","1.3.1","2.0.0","0.4.10","2.7","2.0.2","0.13","1.0.0","2.5-1","0.3.1","1.1.0","1.6.0","3.6.1","1.4.34","3.6.1","3.6.1","1.5.3","1.4.0","3.2-7","1.0-10","3.1.0","1.1.3","1.1.0","1.3.1","3.6.1","1.2.1","3.6.1","0.3.7","2.4.1","0.22","1.3.2","1.8-4","2.2.1","1.8-7"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Generalised Linear Models</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->



<!-- Build Tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
